In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset=pd.read_csv("EMG-data.csv")
dataset.head()

,time,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,class,label
0,1,0.00001,-0.00002,-0.00001,-0.00003,0.00000,-0.00001,0.00000,-0.00001,0,1
1,5,0.00001,-0.00002,-0.00001,-0.00003,0.00000,-0.00001,0.00000,-0.00001,0,1
2,6,-0.00001,0.00001,0.00002,0.00000,0.00001,-0.00002,-0.00001,0.00001,0,1
3,7,-0.00001,0.00001,0.00002,0.00000,0.00001,-0.00002,-0.00001,0.00001,0,1
4,8,-0.00001,0.00001,0.00002,0.00000,0.00001,-0.00002,-0.00001,0.00001,0,1

In [3]:
print("Shape: ",dataset.shape)

Shape:  (4237907, 11)

In [4]:
print("Count of null values: ",dataset.isnull().any().sum())

Count of null values:  0

In [5]:
##drop gesture 0 because it offers no information due to its unmarked nature
index_numbers_1=dataset[dataset["class"]==0].index 
dataset.drop(index_numbers_1,inplace=True)
##drop gesture 7 because it offers no information due to it being performed 
##by just two out of 36 patients 
index_numbers_2=dataset[dataset["class"]==7].index
dataset.drop(index_numbers_2,inplace=True)

In [6]:
dataset.head()

,time,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,class,label
2287,2400,-0.00001,0.00000,-0.00001,0.00000,0.00000,-0.00001,-0.00001,0.00001,1,1
2288,2401,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1
2289,2402,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1
2290,2403,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1
2291,2404,-0.00001,-0.00002,0.00000,-0.00001,-0.00001,-0.00001,-0.00003,-0.00002,1,1

In [7]:
dataset=dataset.drop(columns=["time"])
dataset["class"].value_counts()

class
6    253009
5    251733
4    251570
1    250055
3    249494
2    243193
Name: count, dtype: int64

In [8]:
dataset=dataset.groupby(['label','class'])

In [9]:
##functions for extracting sEMG features
def rms(data): ##root mean square
      return  np.sqrt(np.mean(data**2,axis=0))  

def SSI(data): ##Simple Square Integral
    return np.sum(data**2,axis=0)

def abs_diffs_signal(data): ##absolute differential signal
    return np.sum(np.abs(np.diff(data,axis=0)),axis=0)

##function for returning an estimator class name 
def print_estimator_name(estimator):
    return estimator.__class__.__name__

In [10]:
dataset=dataset.agg(['min','max',rms,SSI,abs_diffs_signal,np.ptp])
dataset.head()

            channel1                                                         \
                 min      max       rms       SSI abs_diffs_signal      ptp
label class
1     1     -0.00005  0.00004  0.000017  0.000002          0.01070  0.00009
      2     -0.00111  0.00095  0.000210  0.000301          0.16819  0.00206
      3     -0.00087  0.00112  0.000188  0.000260          0.14544  0.00199
      4     -0.00020  0.00016  0.000056  0.000022          0.03609  0.00036
      5     -0.00031  0.00061  0.000066  0.000030          0.04939  0.00092

            channel2                               ...  channel7            \
                 min      max       rms       SSI  ...       rms       SSI
label class                                        ...
1     1     -0.00010  0.00007  0.000027  0.000005  ...  0.000013  0.000001
      2     -0.00047  0.00041  0.000117  0.000093  ...  0.000216  0.000318
      3     -0.00113  0.00127  0.000259  0.000493  ...  0.000078  0.000044
      4     -0.00038  0.00024  0.000082  0.000046  ...  0.000118  0.000095
      5     -0.00066  0.00035  0.000125  0.000110  ...  0.000084  0.000049

                                      channel8                               \
            abs_diffs_signal      ptp      min      max       rms       SSI
label class
1     1              0.00870  0.00006 -0.00005  0.00002  0.000014  0.000001
      2              0.16251  0.00153 -0.00070  0.00054  0.000150  0.000153
      3              0.05866  0.00063 -0.00073  0.00051  0.000161  0.000190
      4              0.07517  0.00090 -0.00032  0.00026  0.000083  0.000047
      5              0.06768  0.00055 -0.00030  0.00045  0.000060  0.000025


            abs_diffs_signal      ptp
label class
1     1              0.00921  0.00007
      2              0.11696  0.00124
      3              0.11869  0.00124
      4              0.04984  0.00058
      5              0.04606  0.00075

[5 rows x 48 columns]

In [11]:
dataset=dataset.reset_index()
print(dataset.shape)
dataset.head()

(216, 50)

  label class channel1                                                         \
                   min      max       rms       SSI abs_diffs_signal      ptp
0     1     1 -0.00005  0.00004  0.000017  0.000002          0.01070  0.00009
1     1     2 -0.00111  0.00095  0.000210  0.000301          0.16819  0.00206
2     1     3 -0.00087  0.00112  0.000188  0.000260          0.14544  0.00199
3     1     4 -0.00020  0.00016  0.000056  0.000022          0.03609  0.00036
4     1     5 -0.00031  0.00061  0.000066  0.000030          0.04939  0.00092

  channel2           ...  channel7                                      \
       min      max  ...       rms       SSI abs_diffs_signal      ptp
0 -0.00010  0.00007  ...  0.000013  0.000001          0.00870  0.00006
1 -0.00047  0.00041  ...  0.000216  0.000318          0.16251  0.00153
2 -0.00113  0.00127  ...  0.000078  0.000044          0.05866  0.00063
3 -0.00038  0.00024  ...  0.000118  0.000095          0.07517  0.00090
4 -0.00066  0.00035  ...  0.000084  0.000049          0.06768  0.00055

  channel8
       min      max       rms       SSI abs_diffs_signal      ptp
0 -0.00005  0.00002  0.000014  0.000001          0.00921  0.00007
1 -0.00070  0.00054  0.000150  0.000153          0.11696  0.00124
2 -0.00073  0.00051  0.000161  0.000190          0.11869  0.00124
3 -0.00032  0.00026  0.000083  0.000047          0.04984  0.00058
4 -0.00030  0.00045  0.000060  0.000025          0.04606  0.00075

[5 rows x 50 columns]

In [12]:
dataset.loc[dataset["class"] == 0, "gesture"] = "unmarked data"
dataset.loc[dataset["class"] == 1, "gesture"] = "hand at rest"
dataset.loc[dataset["class"] == 2, "gesture"] = "hand clenched in a fist"
dataset.loc[dataset["class"] == 3, "gesture"] = "wrist flexion"
dataset.loc[dataset["class"] == 4, "gesture"] = "wrist extension"
dataset.loc[dataset["class"] == 5, "gesture"] = "radial deviations"
dataset.loc[dataset["class"] == 6, "gesture"] = "ulnar deviations"
dataset.loc[dataset["class"] == 7, "gesture"] = "extended palm"
dataset.head()

  label class channel1                                                         \
                   min      max       rms       SSI abs_diffs_signal      ptp
0     1     1 -0.00005  0.00004  0.000017  0.000002          0.01070  0.00009
1     1     2 -0.00111  0.00095  0.000210  0.000301          0.16819  0.00206
2     1     3 -0.00087  0.00112  0.000188  0.000260          0.14544  0.00199
3     1     4 -0.00020  0.00016  0.000056  0.000022          0.03609  0.00036
4     1     5 -0.00031  0.00061  0.000066  0.000030          0.04939  0.00092

  channel2           ...  channel7                           channel8  \
       min      max  ...       SSI abs_diffs_signal      ptp      min
0 -0.00010  0.00007  ...  0.000001          0.00870  0.00006 -0.00005
1 -0.00047  0.00041  ...  0.000318          0.16251  0.00153 -0.00070
2 -0.00113  0.00127  ...  0.000044          0.05866  0.00063 -0.00073
3 -0.00038  0.00024  ...  0.000095          0.07517  0.00090 -0.00032
4 -0.00066  0.00035  ...  0.000049          0.06768  0.00055 -0.00030

                                                          \
       max       rms       SSI abs_diffs_signal      ptp
0  0.00002  0.000014  0.000001          0.00921  0.00007
1  0.00054  0.000150  0.000153          0.11696  0.00124
2  0.00051  0.000161  0.000190          0.11869  0.00124
3  0.00026  0.000083  0.000047          0.04984  0.00058
4  0.00045  0.000060  0.000025          0.04606  0.00075

                   gesture

0             hand at rest
1  hand clenched in a fist
2            wrist flexion
3          wrist extension
4        radial deviations

[5 rows x 51 columns]

In [13]:
features=dataset.drop(columns=["label","class","gesture"])
labels=dataset["class"]

C:\Users\eSpark\AppData\Local\Temp\ipykernel_7944\2371433798.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  features=dataset.drop(columns=["label","class","gesture"])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test,y_train,y_test= train_test_split(features,labels,test_size=0.30, random_state=1)

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [17]:
train_X = scaler.transform(X_train)
test_X = scaler.transform(X_test)

In [18]:
mlp = MLPClassifier(hidden_layer_sizes=(50, 50, 50))
mlp.fit(train_X, y_train)

c:\Users\eSpark\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(50, 50, 50))

In [19]:
y_pred = mlp.predict(test_X)
y_pred

array([1, 4, 5, 3, 2, 2, 5, 2, 1, 5, 5, 3, 1, 3, 5, 2, 5, 6, 6, 4, 5, 4,
       6, 6, 6, 1, 6, 4, 3, 4, 2, 1, 3, 3, 2, 6, 1, 4, 2, 4, 5, 5, 1, 4,
       4, 6, 4, 6, 3, 2, 3, 5, 6, 1, 6, 1, 4, 1, 1, 4, 3, 5, 5, 6, 2],
      dtype=int64)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))

[[11  0  0  0  0  0]
 [ 0  7  0  0  1  0]
 [ 0  0  6  0  0  2]
 [ 0  0  0 11  0  1]
 [ 0  0  1  1 11  0]
 [ 0  2  2  0  0  9]]

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        11
           2       0.78      0.88      0.82         8
           3       0.67      0.75      0.71         8
           4       0.92      0.92      0.92        12
           5       0.92      0.85      0.88        13
           6       0.75      0.69      0.72        13

    accuracy                           0.85        65
   macro avg       0.84      0.85      0.84        65
weighted avg       0.85      0.85      0.85        65

In [22]:
accuracy_score(y_test, y_pred)

0.8461538461538461

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam

In [24]:
print(features.shape)

(216, 48)

In [25]:
X_scaled = scaler.fit_transform(features)
# Reshape X to fit into Conv1D (samples, time steps, features)
# Here we assume each gesture instance is treated as a time step (temporal structure)
n_channels = 8  # Assuming 8 channels as features
time_steps = X_scaled.shape[1] // n_channels
X_reshaped = X_scaled.reshape(X_scaled.shape[0], time_steps, n_channels)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, labels, test_size=0.2, random_state=42)
print(n_channels)

8

In [26]:
cnn = Sequential([
    Input(shape=(time_steps, n_channels)),
    Conv1D(filters=64, kernel_size=3, activation='relu', padding='same'),
    MaxPooling1D(pool_size=1),
    Dropout(0.5),
    Conv1D(filters=128, kernel_size=3, activation='relu', padding='same'),
    MaxPooling1D(pool_size=1),
    Dropout(0.5),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(7, activation='softmax')  # Output layer with number of classes
])

# Compile the model
cnn.compile(optimizer=Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',  # Use sparse categorical crossentropy for integer labels
              metrics=['accuracy'])

# Train the model
cnn.fit(X_train, y_train, epochs=30, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - accuracy: 0.1134 - loss: 2.0572 - val_accuracy: 0.6136 - val_loss: 1.5182
Epoch 2/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3758 - loss: 1.5861 - val_accuracy: 0.7045 - val_loss: 1.2569
Epoch 3/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5512 - loss: 1.3943 - val_accuracy: 0.7273 - val_loss: 1.0352
Epoch 4/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5720 - loss: 1.2965 - val_accuracy: 0.7273 - val_loss: 0.8498
Epoch 5/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5878 - loss: 1.1444 - val_accuracy: 0.7045 - val_loss: 0.7104
Epoch 6/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6481 - loss: 0.9655 - val_accuracy: 0.7955 - val_loss: 0.5875
Epoch 7/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6859 - loss: 0.8766 - val_accuracy: 0.8182 - val_loss: 0.5002
Epoch 8/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7249 - loss: 0.7563 - val_accuracy: 0.8182 - val_loss: 0.4531
Epoch 9/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7805 - loss: 0.7163 - val_accuracy: 0.8409 - val_loss: 0.3888
Epoch 10/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7578 - loss: 0.7174 - val_accuracy: 0.8864 - val_loss: 0.3434
Epoch 11/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7559 - loss: 0.6379 - val_accuracy: 0.9091 - val_loss: 0.3039
Epoch 12/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7521 - loss: 0.7291 - val_accuracy: 0.8864 - val_loss: 0.3041
Epoch 13/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7478 - loss: 0.6182 - val_accuracy: 0.8636 - val_loss: 0.3280
Epoch 14/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8386 - loss: 0.6095 - val_accuracy: 0.8864 - val_loss: 0.2956
Epoch 15/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7730 - loss: 0.5701 - val_accuracy: 0.9091 - val_loss: 0.2528
Epoch 16/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8182 - loss: 0.5560 - val_accuracy: 0.9545 - val_loss: 0.2381
Epoch 17/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8217 - loss: 0.5154 - val_accuracy: 0.9318 - val_loss: 0.2468
Epoch 18/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7920 - loss: 0.5426 - val_accuracy: 0.9091 - val_loss: 0.2536
Epoch 19/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8433 - loss: 0.4601 - val_accuracy: 0.8864 - val_loss: 0.2631
Epoch 20/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8071 - loss: 0.5227 - val_accuracy: 0.9091 - val_loss: 0.2423
Epoch 21/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8366 - loss: 0.4747 - val_accuracy: 0.8636 - val_loss: 0.2574
Epoch 22/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8324 - loss: 0.5360 - val_accuracy: 0.8636 - val_loss: 0.2582
Epoch 23/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8395 - loss: 0.4676 - val_accuracy: 0.8864 - val_loss: 0.2510
Epoch 24/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8580 - loss: 0.4144 - val_accuracy: 0.8636 - val_loss: 0.2395
Epoch 25/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8153 - loss: 0.4626 - val_accuracy: 0.8636 - val_loss: 0.2525
Epoch 26/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9015 - loss: 0.4012 - val_accuracy: 0.8636 - val_loss: 0.2650
Epoch 27/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8462 - loss: 0.4613 - val_accuracy: 0.8636 - val_loss: 0.2554
Epoch 28/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8933 - loss: 0.3743 - val_accuracy: 0.9318 - val_loss: 0.2219
Epoch 29/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8283 - loss: 0.4360 - val_accuracy: 0.9091 - val_loss: 0.2131
Epoch 30/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8536 - loss: 0.3730 - val_accuracy: 0.9318 - val_loss: 0.2196

In [27]:
# Evaluate the model
loss, accuracy = cnn.evaluate(X_test, y_test)
print(f'Test accuracy: {accuracy}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9337 - loss: 0.2077
Test accuracy: 0.9318181872367859

In [28]:
predictions = cnn.predict(X_test)

predicted_classes = np.argmax(predictions, axis=1)

accuracy= accuracy_score(y_test, predicted_classes)
accuracy

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

0.9318181818181818

In [29]:
print(X_test.shape)

(44, 6, 8)

In [ ]:
# import pickle
# pickle.dump(cnn, open('model.pkl','wb'))